name: Deploy Task API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH/Rsync
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: "deployer"
          TARGET: "/opt/projects/task-api/"
          ARGS: "-rlgoDIVz --delete --no-perms --no-owner --omit-dir-times"

      - name: Build and Restart Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "deployer"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/projects/task-api

            if [ -f docker-compose.yml ]; then
              docker compose up -d --build --remove-orphans
            else
              echo "docker-compose.yml not found!"
              exit 1
            fi